In [3]:
import numpy as np
import sympy as sym
import numpy.linalg as LA
from sympy import *
from sympy import oo, gamma
from IPython.display import display
from scipy import special
from matplotlib import pyplot as plt
import matplotlib
init_printing(use_latex='mathjax')
x, y, z, t= symbols('x y z t')
r,theta, phi = symbols('r  theta  phi')
f, g, h = symbols('f g h', cls=Function)

In [34]:
row1=[-3,1,8,0]
row2=[2,1,-1,0]
row3=[4,-5,2,6]
row4=[11,-3,1,7]
A=np.array([row1,row2,row3,row4])
u=np.array([1,0,0,0])
v=np.array([0,0,0,1])
eigvals,eigvec=LA.eig(A)
Ak1=LA.matrix_power(A, 8) 
Ak=LA.matrix_power(A, 7) 
largeeigval=(Ak1@u@v)/(Ak@u@v)
largeeigvec=(Ak@u)
largeeigvec=largeeigvec/np.linalg.norm(largeeigvec)

In [66]:
print(largeeigval)
print(largeeigvec)
print(np.real(eigvals))
print(np.real(eigvec))

12.114586801762341
[0.30331567 0.00287733 0.5715912  0.76241382]
[12.10374809 -2.81465955 -2.81465955  0.52557101]
[[ 0.30282436  0.57462183  0.57462183  0.23911626]
 [ 0.00309014 -0.26383179 -0.26383179 -0.62201671]
 [ 0.57133659  0.09205315  0.09205315  0.18312976]
 [ 0.76279903 -0.73404366 -0.73404366 -0.72276007]]


In [87]:
row1=[-3,1,8,0]
row2=[2,1,-1,0]
row3=[4,-5,2,6]
row4=[11,-3,1,7]
A=np.array([row1,row2,row3,row4])
A=np.linalg.inv(A)
u=np.array([1,0,0,0])
v=np.array([1,0,0,0])
Ak1=LA.matrix_power(A, 100) 
Ak=LA.matrix_power(A, 99) 
smalleigval=(Ak1@u@v)/(Ak@u@v)
smalleigvec=(Ak@u)
smalleigvec=smalleigvec/np.linalg.norm(smalleigvec)
print(smalleigval)
print(smalleigvec)

1.9026924778783432
[-0.23911626  0.62201671 -0.18312976  0.72276007]
